name: Cypress Tests

on: 
  push:
    branches:
      - "main"

jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v4.2.2
        with:
          browser: chrome
          env: configFile=cypress.prod
      - name: Setup Pages
        if: always()
        uses: actions/configure-pages@v2
      - name: upload cucumber report
        uses: actions/upload-artifact@v2
        if: always()
        with: 
          name: github-pages
          path: ./cucumber-report.html
      - name: Deploy to GitHub Pages
        if: always()
        id: deployment
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
      
